<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <SampleWindowsSdkVersion>10.0.26100.0</SampleWindowsSdkVersion>
    <WindowsTargetPlatformVersion Condition="'$(MSBuildProjectExtension)' == '.vcxproj' AND '$(WindowsTargetPlatformVersion)' == ''">$(SampleWindowsSdkVersion)</WindowsTargetPlatformVersion>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>